name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@master
    - name: Build Programming Historian
      run:
        bundle install
        sh _build/build.sh
