
name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5.4
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Build and test PH
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        _build/build.sh